slice_name: "\u0421\u0440\u0430\u0432\u043D\u0435\u043D\u0438\u0435 \u043F\u043E\u043A\
  \u0430\u0437\u0430\u0442\u0435\u043B\u0435\u0439 \u0437\u0430\u043A\u0430\u0437\u0430\
  \ (\u0431\u0430\u0437\u0430 \u0434\u0430\u043D\u043D\u044B\u0445 \u0438 CSV)"
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 59__table
  viz_type: table
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 3
  query_mode: aggregate
  groupby:
  - order_dow
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics:
  - avg_total_orders
  - median_total_orders
  - mean_minus_median_total_orders
  - percent_growth_database_vs_csv
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  order_desc: true
  server_page_length: 10
  row_limit: 10000
  percent_metric_calculation: row_limit
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 17
query_context: '{"datasource":{"id":59,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["order_dow"],"metrics":["avg_total_orders","median_total_orders","mean_minus_median_total_orders","percent_growth_database_vs_csv"],"orderby":[["avg_total_orders",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"59__table","viz_type":"table","matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":3,"query_mode":"aggregate","groupby":["order_dow"],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":["avg_total_orders","median_total_orders","mean_minus_median_total_orders","percent_growth_database_vs_csv"],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"order_desc":true,"server_page_length":10,"row_limit":10000,"percent_metric_calculation":"row_limit","table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[17],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 321558fa-0c58-4ae3-a637-759ddfca4501
version: 1.0.0
dataset_uuid: 10719306-5fa1-45ee-8b8e-93963a7780a2
