{
 "title": " Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_numbackends,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Активные подключения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"${db}\"}\r\n",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Среднее подключений (5 мин)",
   "type": "gauge",
   "description": "Усреднение по времени.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pg_stat_database_numbackends{datname=~\"${db}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активные подключения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"${db}\"}\r\n",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Транзакционная активность",
   "type": "timeseries",
   "description": "Количество коммитов и откатов транзакций за последние 5 минут. Он не даёт среднее время выполнения, но показывает активность запросов в базе — чем выше значение, тем больше операций произошло.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(pg_stat_database_xact_commit{datname=~\"${db}\"}[5m])\r\n+\r\nincrease(pg_stat_database_xact_rollback{datname=~\"${db}\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (коммиты+откаты)",
   "type": "timeseries",
   "description": "Полная нагрузка (запросы/сек).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (datname)(\r\n  rate(pg_stat_database_xact_commit{datname=~\"${db}\"}[1m]) +\r\n  rate(pg_stat_database_xact_rollback{datname=~\"${db}\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во пользователей",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count by (rolname)(pg_roles_list_dummy_value)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O активность",
   "type": "timeseries",
   "description": "Показывает частоту выделения и записи буферов PostgreSQL через фоновый процесс bgwriter.\nИндикатор интенсивности I/O операций и нагрузки на память/диск.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_alloc_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время работы",
   "type": "stat",
   "description": "Uptime сервера в часах.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - pg_postmaster_start_time_seconds) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число строк в таблицах",
   "type": "barchart",
   "description": "Общее количество строк по таблицам выбранной базы данных",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(pg_all_db_tables_estimated_rows{database_name=~\"${db}\"}) by (table_name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер БД (GB)",
   "type": "stat",
   "description": "Размер БД в гигабайтах.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"${db}\"} / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "description": "Кол-во коммитов в секунду.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"${db}\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}