{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "label_values(weather_temperature_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Актуальную температуру в городе",
   "type": "gauge",
   "description": "Панель будет показывать актуальную температуру в городе, что полезнее зимой.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура за 5 минут",
   "type": "timeseries",
   "description": "Средняя температура за 5 минут, отображается как график изменения во времени.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"$city\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя скорость ветра по городам",
   "type": "timeseries",
   "description": "Средняя скорость ветра по выбранному городу с динамикой во времени.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg(weather_windspeed_kmh{city=\"$city\"}) by (city)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Температура + Влажность",
   "type": "bargauge",
   "description": "Суммарная метрика температуры и влажности в одном столбике.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "C + %" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$city\"} + weather_humidity_percent{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Изменение облачности за 10 минут",
   "type": "timeseries",
   "description": "Изменение облачности за 10 минут",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "delta(weather_cloudcover_percent{city=\"$city\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее давление",
   "type": "timeseries",
   "description": "Среднее атмосферное давление в выбранном городе.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "avg(weather_pressure_hpa{city=\"$city\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сумма успешных API вызовов",
   "type": "gauge",
   "description": "Суммарное количество успешных вызовов API.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(weather_api_calls_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество обновлений температуры за 30 минут",
   "type": "barchart",
   "description": "Количество обновлений температуры за последние 30 минут.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "count_over_time(weather_temperature_celsius{city=\"$city\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время ответа API больше 0.5 сек",
   "type": "barchart",
   "description": "Визуализирует случаи долгих ответов API, чтобы отслеживать задержки.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "weather_api_response_time_seconds > 0.5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная температура",
   "type": "gauge",
   "description": "Показывает текущую максимальную температуру в выбранном городе.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(weather_temperature_max_celsius{city=\"$city\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}