slice_name: "\u0422\u043E\u043F-10 \u043F\u043E\u043F\u0443\u043B\u044F\u0440\u043D\
  \u044B\u0445 \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u043E\u0432 (\u043F\u043E\
  \ \u0437\u0430\u043A\u0430\u0437\u0430\u043C)"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 41__table
  viz_type: echarts_timeseries_bar
  slice_id: 622
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  x_axis: product_name
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_orders
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 820
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      uuid: 7c053a15-fff8-42d0-a600-db51c5ecf09f
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(total_orders)
    optionName: metric_m13nu1gy8hg_ll6raorifwk
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\u043E\
    \u0434\u0443\u043A\u0442\u0430"
  x_axis_title_margin: 30
  y_axis_title: "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0437\
    \u0430\u043A\u0430\u0437\u043E\u0432"
  y_axis_title_margin: 50
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  show_value: true
  only_total: true
  show_legend: false
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":41,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[],\"extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\
  \",\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1D\"\
  ,\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"product_name\",\"label\":\"product_name\"\
  ,\"expressionType\":\"SQL\"}],\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"\
  advanced_data_type\":null,\"certification_details\":null,\"certified_by\":null,\"\
  column_name\":\"total_orders\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":820,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"LONGINTEGER\",\"type_generic\":0,\"uuid\":\"7c053a15-fff8-42d0-a600-db51c5ecf09f\"\
  ,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"SUM(total_orders)\"\
  ,\"optionName\":\"metric_m13nu1gy8hg_ll6raorifwk\",\"sqlExpression\":null}],\"orderby\"\
  :[[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"total_orders\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":820,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"LONGINTEGER\",\"\
  type_generic\":0,\"uuid\":\"7c053a15-fff8-42d0-a600-db51c5ecf09f\",\"verbose_name\"\
  :null,\"warning_markdown\":null},\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"SUM(total_orders)\",\"optionName\"\
  :\"metric_m13nu1gy8hg_ll6raorifwk\",\"sqlExpression\":null},false]],\"annotation_layers\"\
  :[],\"row_limit\":10,\"series_columns\":[],\"series_limit\":0,\"group_others_when_limit_reached\"\
  :false,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"product_name\"],\"columns\":[],\"aggregates\":{\"SUM(total_orders)\"\
  :{\"operator\":\"mean\"}},\"drop_missing_columns\":false}},{\"operation\":\"flatten\"\
  }]}],\"form_data\":{\"datasource\":\"41__table\",\"viz_type\":\"echarts_timeseries_bar\"\
  ,\"slice_id\":622,\"matrixify_show_column_headers\":true,\"matrixify_mode_columns\"\
  :\"metrics\",\"matrixify_dimension_selection_mode_columns\":\"members\",\"matrixify_dimension_columns\"\
  :{\"dimension\":\"\",\"values\":[]},\"matrixify_topn_value_columns\":10,\"matrixify_topn_order_columns\"\
  :\"desc\",\"matrixify_show_row_labels\":true,\"matrixify_mode_rows\":\"metrics\"\
  ,\"matrixify_dimension_selection_mode_rows\":\"members\",\"matrixify_dimension_rows\"\
  :{\"dimension\":\"\",\"values\":[]},\"matrixify_topn_value_rows\":10,\"matrixify_topn_order_rows\"\
  :\"desc\",\"matrixify_row_height\":300,\"matrixify_fit_columns_dynamically\":true,\"\
  matrixify_charts_per_row\":4,\"x_axis\":\"product_name\",\"time_grain_sqla\":\"\
  P1D\",\"x_axis_sort_asc\":true,\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"\
  advanced_data_type\":null,\"certification_details\":null,\"certified_by\":null,\"\
  column_name\":\"total_orders\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":820,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"LONGINTEGER\",\"type_generic\":0,\"uuid\":\"7c053a15-fff8-42d0-a600-db51c5ecf09f\"\
  ,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"SUM(total_orders)\"\
  ,\"optionName\":\"metric_m13nu1gy8hg_ll6raorifwk\",\"sqlExpression\":null}],\"groupby\"\
  :[],\"adhoc_filters\":[],\"order_desc\":true,\"row_limit\":10,\"truncate_metric\"\
  :true,\"show_empty_columns\":true,\"comparison_type\":\"values\",\"annotation_layers\"\
  :[],\"forecastPeriods\":10,\"forecastInterval\":0.8,\"orientation\":\"vertical\"\
  ,\"x_axis_title\":\"\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\
  \u043E\u0434\u0443\u043A\u0442\u0430\",\"x_axis_title_margin\":30,\"y_axis_title\"\
  :\"\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0437\u0430\u043A\
  \u0430\u0437\u043E\u0432\",\"y_axis_title_margin\":50,\"y_axis_title_position\"\
  :\"Left\",\"sort_series_type\":\"sum\",\"color_scheme\":\"supersetColors\",\"time_shift_color\"\
  :true,\"show_value\":true,\"only_total\":true,\"show_legend\":false,\"legendType\"\
  :\"scroll\",\"legendOrientation\":\"top\",\"x_axis_time_format\":\"smart_date\"\
  ,\"xAxisLabelInterval\":\"auto\",\"y_axis_format\":\"SMART_NUMBER\",\"y_axis_bounds\"\
  :[null,null],\"truncateXAxis\":true,\"rich_tooltip\":true,\"showTooltipTotal\":true,\"\
  tooltipTimeFormat\":\"smart_date\",\"extra_form_data\":{},\"dashboards\":[],\"force\"\
  :false,\"result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"\
  json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 39b037b0-4401-4e49-98b4-c121cd9502f7
version: 1.0.0
dataset_uuid: 4f8c9196-6ca7-4833-9c56-6f8a72c08c2c
