slice_name: "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0437\u0430\
  \u043A\u0430\u0437\u043E\u0432 \u043F\u043E \u0447\u0430\u0441\u0430\u043C \u0441\
  \u0443\u0442\u043E\u043A"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 44__table
  viz_type: echarts_timeseries_line
  slice_id: 625
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  x_axis: order_hour_of_day
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_orders
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 826
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: 1f0e5e38-abf7-416e-94d3-013fd0984bb7
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(total_orders)
    optionName: metric_yi9o6p1ybj_cl1l26x8k5i
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: "\u0427\u0430\u0441 \u0441\u0443\u0442\u043E\u043A (0\u201323)"
  x_axis_title_margin: 30
  y_axis_title: "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0437\
    \u0430\u043A\u0430\u0437\u043E\u0432"
  y_axis_title_margin: 50
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: false
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":44,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[],\"extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\
  \",\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1D\"\
  ,\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"order_hour_of_day\",\"label\"\
  :\"order_hour_of_day\",\"expressionType\":\"SQL\"}],\"metrics\":[{\"aggregate\"\
  :\"SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"total_orders\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":826,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"column\",\"type_generic\"\
  :0,\"uuid\":\"1f0e5e38-abf7-416e-94d3-013fd0984bb7\",\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"SUM(total_orders)\",\"optionName\":\"metric_yi9o6p1ybj_cl1l26x8k5i\"\
  ,\"sqlExpression\":null}],\"orderby\":[[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"total_orders\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":826,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"column\",\"type_generic\":0,\"uuid\":\"1f0e5e38-abf7-416e-94d3-013fd0984bb7\"\
  ,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"SUM(total_orders)\"\
  ,\"optionName\":\"metric_yi9o6p1ybj_cl1l26x8k5i\",\"sqlExpression\":null},false]],\"\
  annotation_layers\":[],\"row_limit\":10000,\"series_columns\":[],\"series_limit\"\
  :0,\"group_others_when_limit_reached\":false,\"order_desc\":true,\"url_params\"\
  :{},\"custom_params\":{},\"custom_form_data\":{},\"time_offsets\":[],\"post_processing\"\
  :[{\"operation\":\"pivot\",\"options\":{\"index\":[\"order_hour_of_day\"],\"columns\"\
  :[],\"aggregates\":{\"SUM(total_orders)\":{\"operator\":\"mean\"}},\"drop_missing_columns\"\
  :false}},{\"operation\":\"flatten\"}]}],\"form_data\":{\"datasource\":\"44__table\"\
  ,\"viz_type\":\"echarts_timeseries_line\",\"slice_id\":625,\"matrixify_show_column_headers\"\
  :true,\"matrixify_mode_columns\":\"metrics\",\"matrixify_dimension_selection_mode_columns\"\
  :\"members\",\"matrixify_dimension_columns\":{\"dimension\":\"\",\"values\":[]},\"\
  matrixify_topn_value_columns\":10,\"matrixify_topn_order_columns\":\"desc\",\"matrixify_show_row_labels\"\
  :true,\"matrixify_mode_rows\":\"metrics\",\"matrixify_dimension_selection_mode_rows\"\
  :\"members\",\"matrixify_dimension_rows\":{\"dimension\":\"\",\"values\":[]},\"\
  matrixify_topn_value_rows\":10,\"matrixify_topn_order_rows\":\"desc\",\"matrixify_row_height\"\
  :300,\"matrixify_fit_columns_dynamically\":true,\"matrixify_charts_per_row\":4,\"\
  x_axis\":\"order_hour_of_day\",\"time_grain_sqla\":\"P1D\",\"x_axis_sort_asc\":true,\"\
  metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"total_orders\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":826,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"column\",\"type_generic\"\
  :0,\"uuid\":\"1f0e5e38-abf7-416e-94d3-013fd0984bb7\",\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"SUM(total_orders)\",\"optionName\":\"metric_yi9o6p1ybj_cl1l26x8k5i\"\
  ,\"sqlExpression\":null}],\"groupby\":[],\"adhoc_filters\":[],\"order_desc\":true,\"\
  row_limit\":10000,\"truncate_metric\":true,\"show_empty_columns\":true,\"comparison_type\"\
  :\"values\",\"annotation_layers\":[],\"forecastPeriods\":10,\"forecastInterval\"\
  :0.8,\"x_axis_title\":\"\u0427\u0430\u0441 \u0441\u0443\u0442\u043E\u043A (0\u2013\
  23)\",\"x_axis_title_margin\":30,\"y_axis_title\":\"\u041A\u043E\u043B\u0438\u0447\
  \u0435\u0441\u0442\u0432\u043E \u0437\u0430\u043A\u0430\u0437\u043E\u0432\",\"y_axis_title_margin\"\
  :50,\"y_axis_title_position\":\"Left\",\"sort_series_type\":\"sum\",\"color_scheme\"\
  :\"supersetColors\",\"time_shift_color\":true,\"seriesType\":\"line\",\"only_total\"\
  :true,\"opacity\":0.2,\"markerSize\":6,\"show_legend\":false,\"legendType\":\"scroll\"\
  ,\"legendOrientation\":\"top\",\"x_axis_time_format\":\"smart_date\",\"xAxisLabelInterval\"\
  :\"auto\",\"rich_tooltip\":true,\"showTooltipTotal\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"y_axis_format\":\"SMART_NUMBER\",\"truncateXAxis\":true,\"y_axis_bounds\"\
  :[null,null],\"extra_form_data\":{},\"dashboards\":[],\"force\":false,\"result_format\"\
  :\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"\
  full\"}"
cache_timeout: null
uuid: 0591d7a1-d5c2-4dee-86b7-3665e9edb163
version: 1.0.0
dataset_uuid: 59523ea4-feb6-4393-b03f-987f626d11da
