table_name: products_by_dept_aisle
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: instacart_db
schema: public
sql: "SELECT d.department, a.aisle, COUNT(*) AS cnt\r\nFROM products p\r\nJOIN departments\
  \ d ON p.department_id = d.department_id\r\nJOIN aisles a ON p.aisle_id = a.aisle_id\r\
  \nGROUP BY d.department, a.aisle\r\nORDER BY d.department, a.aisle;\r\n"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
folders: null
uuid: c85e4731-4d40-4188-ab4c-476610ffec2a
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: cnt
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: department
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: aisle
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: bf77b44e-1c15-469d-8d56-861e70d2247e
