slice_name: "\u0410\u043A\u0442\u0438\u0432\u043D\u043E\u0441\u0442\u044C \u0442\u043E\
  \u043F-5 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\
  \u0439 \u043F\u043E \u0434\u043D\u044F\u043C \u043D\u0435\u0434\u0435\u043B\u0438"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 37__table
  viz_type: echarts_timeseries_line
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  x_axis: order_dow
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: orders_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 811
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: 63385cc2-7469-490f-b41d-414f617e9752
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(orders_count)
    optionName: metric_rrjko450n7_5uojvtb8nw7
  groupby:
  - user_id
  adhoc_filters: []
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: "\u0414\u0435\u043D\u044C \u043D\u0435\u0434\u0435\u043B\u0438 (0=\u0412\
    \u0441 ... 6=\u0421\u0431)"
  x_axis_title_margin: 30
  y_axis_title: "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0437\
    \u0430\u043A\u0430\u0437\u043E\u0432"
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: name
  sort_series_ascending: false
  color_scheme: supersetColors
  time_shift_color: true
  seriesType: line
  show_value: false
  only_total: true
  area: false
  opacity: 0.2
  markerEnabled: false
  markerSize: 6
  zoomable: false
  minorTicks: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendMargin: null
  legendSort: null
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":37,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[],\"extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\
  \",\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1D\"\
  ,\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"order_dow\",\"label\":\"order_dow\"\
  ,\"expressionType\":\"SQL\"},\"user_id\"],\"metrics\":[{\"expressionType\":\"SIMPLE\"\
  ,\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\"\
  :null,\"column_name\":\"orders_count\",\"description\":null,\"expression\":null,\"\
  filterable\":true,\"groupby\":true,\"id\":811,\"is_certified\":false,\"is_dttm\"\
  :false,\"python_date_format\":null,\"type\":\"column\",\"type_generic\":0,\"uuid\"\
  :\"63385cc2-7469-490f-b41d-414f617e9752\",\"verbose_name\":null,\"warning_markdown\"\
  :null},\"aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"\
  hasCustomLabel\":false,\"label\":\"SUM(orders_count)\",\"optionName\":\"metric_rrjko450n7_5uojvtb8nw7\"\
  }],\"orderby\":[[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"orders_count\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":811,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"column\",\"type_generic\":0,\"uuid\":\"63385cc2-7469-490f-b41d-414f617e9752\"\
  ,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"SUM(orders_count)\"\
  ,\"optionName\":\"metric_rrjko450n7_5uojvtb8nw7\"},false]],\"annotation_layers\"\
  :[],\"row_limit\":10000,\"series_columns\":[\"user_id\"],\"series_limit\":0,\"group_others_when_limit_reached\"\
  :false,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"order_dow\"],\"columns\":[\"user_id\"],\"aggregates\":{\"SUM(orders_count)\"\
  :{\"operator\":\"mean\"}},\"drop_missing_columns\":false}},{\"operation\":\"rename\"\
  ,\"options\":{\"columns\":{\"SUM(orders_count)\":null},\"level\":0,\"inplace\":true}},{\"\
  operation\":\"flatten\"}]}],\"form_data\":{\"datasource\":\"37__table\",\"viz_type\"\
  :\"echarts_timeseries_line\",\"matrixify_show_column_headers\":true,\"matrixify_mode_columns\"\
  :\"metrics\",\"matrixify_dimension_selection_mode_columns\":\"members\",\"matrixify_dimension_columns\"\
  :{\"dimension\":\"\",\"values\":[]},\"matrixify_topn_value_columns\":10,\"matrixify_topn_order_columns\"\
  :\"desc\",\"matrixify_show_row_labels\":true,\"matrixify_mode_rows\":\"metrics\"\
  ,\"matrixify_dimension_selection_mode_rows\":\"members\",\"matrixify_dimension_rows\"\
  :{\"dimension\":\"\",\"values\":[]},\"matrixify_topn_value_rows\":10,\"matrixify_topn_order_rows\"\
  :\"desc\",\"matrixify_row_height\":300,\"matrixify_fit_columns_dynamically\":true,\"\
  matrixify_charts_per_row\":4,\"x_axis\":\"order_dow\",\"time_grain_sqla\":\"P1D\"\
  ,\"x_axis_sort_asc\":true,\"metrics\":[{\"expressionType\":\"SIMPLE\",\"column\"\
  :{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\":null,\"\
  column_name\":\"orders_count\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":811,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"column\",\"type_generic\":0,\"uuid\":\"63385cc2-7469-490f-b41d-414f617e9752\"\
  ,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"SUM(orders_count)\"\
  ,\"optionName\":\"metric_rrjko450n7_5uojvtb8nw7\"}],\"groupby\":[\"user_id\"],\"\
  adhoc_filters\":[],\"order_desc\":true,\"row_limit\":10000,\"truncate_metric\":true,\"\
  show_empty_columns\":true,\"comparison_type\":\"values\",\"annotation_layers\":[],\"\
  forecastPeriods\":10,\"forecastInterval\":0.8,\"x_axis_title\":\"\u0414\u0435\u043D\
  \u044C \u043D\u0435\u0434\u0435\u043B\u0438 (0=\u0412\u0441 ... 6=\u0421\u0431)\"\
  ,\"x_axis_title_margin\":30,\"y_axis_title\":\"\u041A\u043E\u043B\u0438\u0447\u0435\
  \u0441\u0442\u0432\u043E \u0437\u0430\u043A\u0430\u0437\u043E\u0432\",\"y_axis_title_margin\"\
  :30,\"y_axis_title_position\":\"Left\",\"sort_series_type\":\"name\",\"sort_series_ascending\"\
  :false,\"color_scheme\":\"supersetColors\",\"time_shift_color\":true,\"seriesType\"\
  :\"line\",\"show_value\":false,\"only_total\":true,\"area\":false,\"opacity\":0.2,\"\
  markerEnabled\":false,\"markerSize\":6,\"zoomable\":false,\"minorTicks\":false,\"\
  show_legend\":true,\"legendType\":\"scroll\",\"legendOrientation\":\"top\",\"legendMargin\"\
  :null,\"legendSort\":null,\"x_axis_time_format\":\"smart_date\",\"xAxisLabelInterval\"\
  :\"auto\",\"rich_tooltip\":true,\"showTooltipTotal\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"y_axis_format\":\"SMART_NUMBER\",\"truncateXAxis\":true,\"truncateYAxis\"\
  :false,\"y_axis_bounds\":[null,null],\"extra_form_data\":{},\"dashboards\":[],\"\
  force\":false,\"result_format\":\"json\",\"result_type\":\"full\"},\"result_format\"\
  :\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 0e81159d-0e2b-4045-8fb2-0f09132225c2
version: 1.0.0
dataset_uuid: f82ce524-0f0a-41ef-b480-90c7f767787a
